[package]
name = "libopenraw"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
lazy_static = "1.4.0"
log = "0.4.14"
mp4parse = { path = "lib/mp4/mp4parse", version = "0.11.4", features = [ "craw" ] }
once_cell = "1.9.0"
simple_logger = "2.1.0"

[workspace]
members = [
    "lib/mp4/mp4parse"
]


[[bin]]
name = "ordump"
test = false
bench = false