/*
 * libopenraw - panasonic.rs
 *
 * Copyright (C) 2022 Hubert Figuière
 *
 * This library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.  If not, see
 * <http://www.gnu.org/licenses/>.
 */

//! Panasonic camera support (and some Leica)

use std::collections::HashMap;

lazy_static::lazy_static! {
    pub static ref MNOTE_TAG_NAMES: HashMap<u16, &'static str> = HashMap::from([
        (0x1, "ImageQuality"),
        (0x2, "FirmwareVersion"),
        (0x3, "WhiteBalance"),
        (0x7, "FocusMode"),
        (0xf, "AFAreaMode"),
        (0x1a, "ImageStabilization"),
        (0x1c, "MacroMode"),
        (0x1f, "ShootingMode"),
        (0x20, "Audio"),
        (0x21, "DataDump"),
        (0x23, "WhiteBalanceBias"),
        (0x24, "FlashBias"),
        (0x25, "InternalSerialNumber"),
        (0x26, "PanasonicExifVersion"),
        (0x28, "ColorEffect"),
        (0x29, "TimeSincePowerOn"),
        (0x2a, "BurstMode"),
        (0x2b, "SequenceNumber"),
        (0x2c, "ContrastMode"),
        (0x2d, "NoiseReduction"),
        (0x2e, "SelfTimer"),
        (0x30, "Rotation"),
        (0x31, "AFAssistLamp"),
        (0x32, "ColorMode"),
        (0x33, "BabyAge"),
        (0x34, "OpticalZoomMode"),
        (0x35, "ConversionLens"),
        (0x36, "TravelDay"),
        (0x39, "Contrast"),
        (0x3a, "WorldTimeLocation"),
        (0x3b, "TextStamp"),
        (0x3c, "ProgramISO"),
        (0x3d, "AdvancedSceneType"),
        (0x3e, "TextStamp"),
        (0x3f, "FacesDetected"),
        (0x40, "Saturation"),
        (0x41, "Sharpness"),
        (0x42, "FilmMode"),
        (0x43, "JPEGQuality"),
        (0x44, "ColorTempKelvin"),
        (0x45, "BracketSettings"),
        (0x46, "WBShiftAB"),
        (0x47, "WBShiftGM"),
        (0x48, "FlashCurtain"),
        (0x49, "LongExposureNoiseReduction"),
        (0x4b, "PanasonicImageWidth"),
        (0x4c, "PanasonicImageHeight"),
        (0x4d, "AFPointPosition"),
        (0x4e, "FaceDetInfo"),
        (0x51, "LensType"),
        (0x52, "LensSerialNumber"),
        (0x53, "AccessoryType"),
        (0x54, "AccessorySerialNumber"),
        (0x59, "Transform"),
        (0x5d, "IntelligentExposure"),
        (0x60, "LensFirmwareVersion"),
        (0x61, "FaceRecInfo"),
        (0x62, "FlashWarning"),
        (0x63, "RecognizedFaceFlags"),
        (0x65, "Title"),
        (0x66, "BabyName"),
        (0x67, "Location"),
        (0x69, "Country"),
        (0x6b, "State"),
        (0x6d, "City"),
        (0x6f, "Landmark"),
        (0x70, "IntelligentResolution"),
        (0x76, "HDRShot"),
        (0x77, "BurstSpeed"),
        (0x79, "IntelligentD-Range"),
        (0x7c, "ClearRetouch"),
        (0x80, "City2"),
        (0x86, "ManometerPressure"),
        (0x89, "PhotoStyle"),
        (0x8a, "ShadingCompensation"),
        (0x8b, "WBShiftIntelligentAuto"),
        (0x8c, "AccelerometerZ"),
        (0x8d, "AccelerometerX"),
        (0x8e, "AccelerometerY"),
        (0x8f, "CameraOrientation"),
        (0x90, "RollAngle"),
        (0x91, "PitchAngle"),
        (0x92, "WBShiftCreativeControl"),
        (0x93, "SweepPanoramaDirection"),
        (0x94, "SweepPanoramaFieldOfView"),
        (0x96, "TimerRecording"),
        (0x9d, "InternalNDFilter"),
        (0x9e, "HDR"),
        (0x9f, "ShutterType"),
        (0xa1, "FilterEffect"),
        (0xa3, "ClearRetouchValue"),
        (0xa7, "OutputLUT"),
        (0xab, "TouchAE"),
        (0xac, "MonochromeFilterEffect"),
        (0xad, "HighlightShadow"),
        (0xaf, "TimeStamp"),
        (0xb3, "VideoBurstResolution"),
        (0xb4, "MultiExposure"),
        (0xb9, "RedEyeRemoval"),
        (0xbb, "VideoBurstMode"),
        (0xbc, "DiffractionCorrection"),
        (0xbd, "FocusBracket"),
        (0xbe, "LongExposureNRUsed"),
        (0xbf, "PostFocusMerging"),
        (0xc1, "VideoPreburst"),
        (0xc4, "LensTypeMake"),
        (0xc5, "LensTypeModel"),
        (0xd1, "ISO"),
        (0xd2, "MonochromeGrainEffect"),
        (0xd6, "NoiseReductionStrength"),
        (0xe00, "PrintIM"),
        (0x2003, "TimeInfo"),
        (0x8000, "MakerNoteVersion"),
        (0x8001, "SceneMode"),
        (0x8002, "HighlightWarning"),
        (0x8003, "DarkFocusEnvironment"),
        (0x8004, "WBRedLevel"),
        (0x8005, "WBGreenLevel"),
        (0x8006, "WBBlueLevel"),
        (0x8008, "TextStamp"),
        (0x8009, "TextStamp"),
        (0x8010, "BabyAge"),
        (0x8012, "Transform"),
    ]);
}
